### ISSUE TITLE
dehumidifierMode values

### ISSUE THREAD

**Issue by rrman** [haywirecoder/homebridge-frigidaire-dehumidifier#1]
Hi,

Thanks for publishing the plug-in! Some questions: t

1. The documentation says that dehumidiferMode only has two values: auto and dehumidifying. The example configuration has:

"dehumidifierMode": 9

Can you confirm what are the valid values for dehumidiferMode in the .json config file?

2. I have two Frigidaire dehumidifiers (model FGAC5044W1). Both dehumidifiers are in the same account. Does the plug-in support more than one dehumidifier?

Regards,

Randy

**Comment by haywirecoder** [comment]
Hi
1. Homekit only has two modes for dehumider either "Auto" or "Dehumidifying". In contrast, the Frigidaire has 4 modes - Auto, Dry, Continous, and Quiet. Rather than the plug-in being hardcoded to "Dry" for Dehumidifying", it allows the user to select what Homekit "dehumidifying" mode map to which Frigidaire function. In the example configuration "9" is Quiet mode. The UX configurator (e.g. .json) set the default value to "Dry",  if the dehumidifierMode attribute is not set or not in the configuration file the defaults to "Dry". I will update the readme to make this clearer.

2. Yes, it written to support multiple devices. When the plugin starts, it automatically reads all appliances in your account, if the appliance is a dehumidifier it exposes it to Homekit. You can confirm the correct mapping by looking at SN in properties of devices when it is created in the Home App. If this doesn't work please let me know, this is not a use case I can test since I only have one device, but the plug-in is written to support multiple appliances at once.

**Comment by rrman** [comment]
Thanks. Yes, it would be good to document the integer values to use for auto, quiet, and continuous as well. 

Regards,

Randy

**Comment by haywirecoder** [comment]
Done, 
It's now publish in the Readme in the repo and the package will be publish shortly. Noted the Air Purifier attribute was incorrect, updated the configure (.json), the code and document. Shouldn't be impactful, unless you disable the Air purifier in your configure, otherwise will need to change enableAirFilter to enableAirPurifier. UX will also clear and fix it as well.

**Comment by rrman** [comment]
Thanks!

**Comment by haywirecoder** [comment]
Document updated and packaged publish.
